priority: 0

ServerEvents.recipes(event => {

	event.remove({ id: 'alexscaves:gunpowder_from_sulfur' })
	event.remove({ id: 'neapolitan:mixed/neapolitan_ice_cream_from_vanilla' })
	event.remove({ id: 'supplementaries:string' })
	event.remove({ id: 'farmersdelight:cooking/apple_cider' })
	event.remove({ id: 'farmersdelight:cooking/hot_cocoa' })
	event.remove({ id: 'minecraft:blue_dye' })
	event.remove({ id: 'minecraft:gunpowder' })
	event.remove({ id: 'abnormals_delight:upgrade_aquatic/cutting/purple_pickerelweed' })
	event.remove({ id: 'abnormals_delight:caverns_and_chasms/silver_nugget_from_blasting_knife' })
	event.remove({ id: 'abnormals_delight:caverns_and_chasms/silver_nugget_from_smelting_knife' })
	event.remove({ id: 'minecraft:chest' })
	event.remove({ id: 'minecraft:bookshelf' })
	event.remove({ id: 'farmersrespite:chilidog_alt'})
	event.remove({ id: 'nethersdelight:cutting/hoglin_sausage_alt'})
	event.remove({ id: 'minecraft:loadstone'})
	event.remove({ id: 'quark:building/crafting/compressed/nether_wart_block_override'})
	event.remove({ id: 'quark:tools/smelting/trowel_to_iron_nugget'})
	event.remove({ id: 'abnormals_delight:environmental/cooking/truffle_mash' })
	event.remove({ id: 'minecraft:lead' })
//	event.remove({ id: 'clash:rod_of_gales_temporary' })
	event.remove({ id: 'caverns_and_chasms:copper_ingot_from_nuggets' })
	event.remove({ id: 'caverns_and_chasms:copper_nugget' })
	event.remove({ id: 'mynethersdelight:basket_alt' })
	event.remove({ id: 'mynethersdelight:stick_alt' })
	event.remove({ id: 'mynethersdelight:tnt_alt' })
	event.remove({ id: 'mynethersdelight:scaffolding_alt' })
//	event.remove({ id: 'cavedelight:dino_nugget_platter' })
	event.remove({ id: 'brewinandchewin:quiche_from_bacon' })
//	event.remove({ id: 'cavedelight:volcanic_chop_from_dinosaur_cut' })
	event.remove({ id: 'naturalist:cake' })
	event.remove({ id: 'farmersdelight:integration/create/mixing/cabbage_slice_from_mixing' })
	event.remove({ id: 'nirvana:lead_from_hemp'})
	event.remove({ id: 'mynethersdelight:crafting/tnt_alt'})
	event.remove({ id: 'quark:building/crafting/furnaces/cobblestone_furnace'})
	event.remove({ id: 'quark:building/crafting/furnaces/blackstone_minecart'})
	event.remove({ id: 'quark:building/crafting/furnaces/blackstone_smoker'})
	event.remove({ id: 'quark:building/crafting/furnaces/blackstone_blast_furnace'})
	event.remove({ id: 'quark:building/crafting/furnaces/deepslate_blast_furnace'})
	event.remove({ id: 'quark:building/crafting/furnaces/deepslate_smoker'})
	event.remove({ id: 'quark:building/crafting/furnaces/deepslate_minecart'})
	event.remove({ id: 'minecraft:andesite'})
	event.remove({ id: 'minecraft:diorite'})
	event.remove({ id: 'minecraft:granite'})
	event.remove({ id: 'caverns_and_chasms:tuff'})
	event.remove({ id: 'caverns_and_chasms:calcite'})
//	event.remove({ id: 'sullysmod:crafting/arrow_from_arrowhead'})
//	event.remove({ id: 'sullysmod:crafting/arrow_from_piranha_tooth'})
//	event.remove({ id: 'species:arrow_from_werefang'})
	event.remove({ id: 'naturalist:spectral_arrow_from_glow_goop'})
	event.remove({ id: 'dungeonsdelight:monster_cooking/misc/wardenzola'})
	event.remove({ id: 'create:smelting/glass_from_horizontal_framed_glass' })
	event.remove({ id: 'create:smelting/glass_from_tiled_glass' })
	event.remove({ id: 'create:smelting/glass_from_vertical_framed_glass' })
	event.remove({ id: 'create:smelting/glass_pane_from_horizontal_framed_glass_pane' })
	event.remove({ id: 'create:smelting/glass_pane_from_tiled_glass_pane' })
	event.remove({ id: 'create:smelting/glass_pane_from_vertical_framed_glass_pane' })
//	event.remove({ id: 'clash:billhook_smithing' })
	event.remove({ id: 'minersdelight:cutting/bat_wing' })
	event.remove({ id: 'minersdelight:cutting/ghasmati' })
	event.remove({ id: 'minecraft:blaze_powder' })
//	event.remove({ id: 'cavedelight:cutting/pinenut_pie' })
	event.remove({ id: 'dungeonsdelight:monster_cooking/misc/rubaboo_from_honey_bottle' })
	event.remove({ id: 'dungeonsdelight:monster_cooking/misc/rubaboo_from_honey_bottle' })
	event.remove({ id: 'dungeonsdelight:monster_cooking/misc/rubaboo_from_sugar' })
	event.remove({ id: 'dungeonsdelight:monster_cooking/misc/rubaboo_from_sweet_berries' })
	event.remove({ id: 'create:mixing/andesite_alloy_from_zinc' })
	event.remove({ id: 'create:mixing/andesite_alloy' })
	event.remove({ id: 'farmersdelight:integration/create/mixing/tomato_sauce_from_mixing' })
	event.remove({ id: 'farmersdelight:integration/create/mixing/pie_crust_from_mixing' })
	event.remove({ id: 'minersdelight:create/emptying/empty_milk_cup' })
	event.remove({ id: 'minersdelight:create/emptying/empty_water_cup' })
	event.remove({ id: 'minersdelight:create/filling/fill_milk_cup' })
	event.remove({ id: 'minersdelight:create/filling/fill_water_cup' })
	event.remove({ id: 'brewinandchewin:emptying/create/milk_bottle' })
	event.remove({ id: 'brewinandchewin:emptying/create/milk_bucket' })
	event.remove({ id: 'brewinandchewin:emptying/create/water_bucket' })
	event.remove({ id: 'brewinandchewin:filling/create/milk_bottle' })
	event.remove({ id: 'brewinandchewin:filling/create/milk_bucket' })
	event.remove({ id: 'brewinandchewin:filling/create/water_bucket' })
	event.remove({ id: 'create:emptying/compat/neapolitan/milk_bottle' })
	event.remove({ id: 'create:emptying/builders_tea' })
	event.remove({ id: 'create:filling/builders_tea' })
	event.remove({ id: 'create:compacting/diorite_from_flint' })
	event.remove({ id: 'create:compacting/granite_from_flint' })
	event.remove({ id: 'create:compacting/andesite_from_flint' })
	event.remove({ id: 'create:sequenced_assembly/sturdy_sheet' })
	event.remove({ id: 'farmersdelight:cutting/sandstone' })
	event.remove({ id: 'farmersdelight:cutting/glass' })
	event.remove({ id: 'farmersdelight:cutting/red_sandstone' })
	event.remove({ id: 'quark:building/smelting/moss_paste' })
	event.remove({ id: 'create:crafting/appliances/item_frame' })
	event.remove({ id: 'spawn:tuna_sandwich_fd' })
	event.remove({ id: 'spawn:tnt_from_blasted_sand' })
//	event.remove({ id: 'opposing_force:wooden_mask' })
//	event.remove({ id: 'opposing_force:wooden_cover' })
	event.remove({ id: 'spawn:bone_meal_from_dead_sea_star' })
	event.remove({ id: 'brewinandchewin:quiche_from_bacon' })
	event.remove({ id: 'galosphere:block_comparator' })
	event.remove({ id: 'windswept:baking/smooth_lunalite_baking' })
	event.remove({ id: 'windswept:shale' })
	event.remove({ id: 'cavedelight:cutting/dinosaur_chop_axe' })
	event.remove({ id: 'neapolitan:strawberry/strawberry_pips_from_white_strawberries' })

// For fuck's sake check the path to the recipe you're trying to overwrite
	event.remove({ id: 'farmersdelight:cookies_from_dough' })
	event.remove({ id: 'farmersdelight:cookies_from_wheat' })
	event.remove({ id: 'farmersdelight:sweet_berry_cookies_from_dough' })
	event.remove({ id: 'farmersdelight:sweet_berry_cookies_from_wheat' })
	event.remove({ id: 'farmersdelight:cooking/cooked_salmon' })
	event.remove({ id: 'farmersdelight:cooking/cooked_chicken' })
	event.remove({ id: 'farmersdelight:cooking/cooked_rabbit' })
	event.remove({ id: 'farmersdelight:cooking/cooked_cod' })
	event.remove({ id: 'farmersdelight:cooking/cooked_mutton_chops' })
	event.remove({ id: 'farmersdelight:cooking/beef_patty' })
	event.remove({ id: 'farmersdelight:cooking/cooked_porkchop' })
	event.remove({ id: 'farmersdelight:cooking/cooked_beef' })
	event.remove({ id: 'farmersdelight:cooking/cooked_cod_slices' })
	event.remove({ id: 'farmersdelight:cooking/cooked_salmon_slices' })
	event.remove({ id: 'farmersdelight:cooking/cooked_bacon' })
	event.remove({ id: 'farmersdelight:cooking/cooked_chicken_cuts' })
	event.remove({ id: 'farmersdelight:cooking/cooked_mutton' })
	event.remove({ id: 'farmersdelight:pumpkin_pie' })
	event.remove({ id: 'farmersdelight:cake_from_dough' })
	event.remove({ id: 'farmersdelight:cake_from_wheat' })
	event.remove({ id: 'farmersdelight:shepherds_pie' })
	event.remove({ id: 'farmersdelight:bread_from_wheat' })
	event.remove({ id: 'farmersdelight:honey_glazed_ham' })
	event.remove({ id: 'farmersdelight:roast_chicken' })
	event.remove({ id: 'farmersdelight:ratatouille' })
	event.remove({ id: 'brewinandchewin:horror_lasagna' })
	event.remove({ id: 'brewinandchewin:pizza_from_dough' })
	event.remove({ id: 'brewinandchewin:pizza_from_wheat' })
	event.remove({ id: 'brewinandchewin:quiche_bacon' })
	event.remove({ id: 'brewinandchewin:quiche_mushroom' })

// God damn it remove your non-functional recipes you bufoons
//	event.remove({ id: 'cavedelight:dino_nugget_platter'})
//	event.remove({ id: 'dungeonsdelight:monster_cooking/meals/coleslaw'})
//	event.remove({ id: 'dungeonsdelight:monster_cooking/meals/gunpowder_baked_spider'})
//	event.remove({ id: 'dungeonsdelight:monster_cooking/misc/dynamite_roll'})
//	event.remove({ id: 'dolt_mod_how:verdant_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:ginger_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:maroon_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:beige_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:tan_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:slate_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:indigo_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:rose_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:aqua_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:teal_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:olive_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:mint_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:forest_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:coral_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:amber_encased_pipe'})
//	event.remove({ id: 'dolt_mod_how:navy_encased_pipe'})
		
// Removing extra baking good recipes
	event.remove({ id: 'alexscaves:cake_from_cake_layer'})
	event.remove({ id: 'naturalist:pumpkin_pie'})
	event.remove({ id: 'create:campfire_cooking/bread'})
	event.remove({ id: 'create:smelting/bread'})
	event.remove({ id: 'create:smoking/bread'})
	event.remove({ id: 'mynethersdelight:bread_from_smelting'})
	event.remove({ id: 'mynethersdelight:bread_from_smoking'})
//	event.remove({ id: 'sob:campfire_cooking/cinder_bread'})
	event.remove({ id: 'minecraft:farmersdelight.dough'})

// Fixing moss
	event.remove({ id: 'minecraft:mossy_cobblestone_from_vine'})
	event.remove({ id: 'minecraft:mossy_cobblestone_from_moss_block'})
	event.remove({ id: 'minecraft:mossy_stone_bricks_from_vine'})
	event.remove({ id: 'minecraft:mossy_stone_bricks_from_moss_block'})
	event.remove({ id: 'caverns_and_chasms:mossy_cobblestone_bricks_from_vine'})
	event.remove({ id: 'caverns_and_chasms:mossy_cobblestone_tiles_from_vine'})

//Fixing Fire
	event.remove({ id: 'netherexp:torch_from_fossil_fuel'})
	event.remove({ id: 'netherexp:soul_torch_from_fossil_fuel'})
	event.remove({ id: 'netherexp:treacherous_torch_from_fossil_fuel'})
	event.remove({ id: 'suppsquared:copper_lantern_2'})	

//Fixing Eggs
//	event.remove({ id: 'cavedelight:fried_egg_dinosaur' })
//	event.remove({ id: 'cavedelight:fried_egg_dinosaur_from_campfire' })
//	event.remove({ id: 'cavedelight:fried_egg_dinosaur_from_smoking' })
	event.remove({ id: 'mynethersdelight:boiled_egg_from_campfire_cooking' })
	event.remove({ id: 'mynethersdelight:boiled_egg_from_smoking' })


//Fixing Create
	event.remove({ id: 'create:crafting/appliances/chain_from_zinc' })
	event.remove({ id: 'create:crafting/kinetics/encased_chain_drive_from_zinc' })
	event.remove({ id: 'create:compacting/chocolate' })
	event.remove({ id: 'create:crafting/kinetics/speedometer_from_conversion' })
	event.remove({ id: 'create:crafting/kinetics/fluid_pipe_vertical' })
	event.remove({ id: 'create:crafting/kinetics/copper_valve_handle_from_others' })
	event.remove({ id: 'create:crafting/kinetics/copper_valve_handle_from_others' })
	event.remove({ id: 'create:brass_bars_from_ingots_brass_stonecutting' })
	event.remove({ id: 'create:brass_ladder_from_ingots_brass_stonecutting' })
	event.remove({ id: 'create:brass_scaffolding_from_ingots_brass_stonecutting' })
	event.remove({ id: 'create:brass_table_cloth_from_ingots_brass_stonecutting' })
	event.remove({ id: 'create:andesite_bars_from_ingots_brass_stonecutting' })
	event.remove({ id: 'create:andesite_ladder_from_ingots_brass_stonecutting' })
	event.remove({ id: 'create:andesite_scaffolding_from_ingots_brass_stonecutting' })
	event.remove({ id: 'create:andesite_table_cloth_from_ingots_brass_stonecutting' })
	event.remove({ id: 'create:framed_glass_from_glass_colorless_stonecutting' })
	event.remove({ id: 'create:framed_glass_pane_from_glass_panes_colorless_stonecutting' })
	event.remove({ id: 'create:horizontal_framed_glass_from_glass_colorless_stonecutting' })
	event.remove({ id: 'create:horizontal_framed_glass_pane_from_glass_panes_colorless_stonecutting' })
	event.remove({ id: 'create:tiled_glass_from_glass_colorless_stonecutting' })
	event.remove({ id: 'create:tiled_glass_pane_from_glass_panes_colorless_stonecutting' })
	event.remove({ id: 'create:crafting/appliances/slime_ball' })
	event.remove({ id: 'create:item_application/andesite_casing_from_wood' })
	event.remove({ id: 'create:item_application/brass_casing_from_wood' })
	event.remove({ id: 'create:item_application/copper_casing_from_wood' })
	event.remove({ id: 'create:vertical_framed_glass_pane_from_glass_panes_colorless_stonecutting' })
	event.remove({ id: 'create:industrial_iron_block_from_ingots_iron_stonecutting' })
	event.remove({ id: 'create:crafting/curiosities/cake' })
	event.remove({ id: 'create:crushing/crimsite_recycling' })
	event.remove({ id: 'create:crushing/ochrum_recycling' })
	event.remove({ id: 'create:sandpaper_polishing/rose_quartz' })
	event.remove({ id: 'create:mixing/tea' })

//Fixing Frame Changer's weird recipes
	event.remove({ id: 'frame_changer:mixing/portal_fluid_from_crying_chiseled_obsidian' })
	event.remove({ id: 'frame_changer:mixing/portal_fluid_from_crying_obsidian_bricks' })
	event.remove({ id: 'frame_changer:mixing/portal_fluid_from_crying_obsidian_pillar' })
	event.remove({ id: 'frame_changer:mixing/portal_fluid_from_crying_polished_obsidian' })

	
//Fixing multiple ore recipes
	event.remove({ id: 'caverns_and_chasms:silver_ingot_from_blasting_deepslate_silver_ore' })
	event.remove({ id: 'caverns_and_chasms:silver_ingot_from_smelting_deepslate_silver_ore' })
	event.remove({ id: 'caverns_and_chasms:silver_ingot_from_blasting_soul_silver_ore' })
	event.remove({ id: 'caverns_and_chasms:silver_ingot_from_smelting_soul_silver_ore' })
	event.remove({ id: 'caverns_and_chasms:spinel_from_blasting_deepslate_spinel_ore' })
	event.remove({ id: 'caverns_and_chasms:spinel_from_smelting_deepslate_spinel_ore' })
	event.remove({ id: 'caverns_and_chasms:tin_ingot_from_blasting_deepslate_tin_ore' })
	event.remove({ id: 'caverns_and_chasms:tin_ingot_from_blasting_cassiterite_tin_ore' })
	event.remove({ id: 'caverns_and_chasms:tin_ingot_from_smelting_deepslate_tin_ore' })
	event.remove({ id: 'caverns_and_chasms:tin_ingot_from_smelting_cassiterite_tin_ore' })
	event.remove({ id: 'caverns_and_chasms:tin_ingot_from_blasting_deepslate_turquoise_ore' })
	event.remove({ id: 'caverns_and_chasms:tin_ingot_from_smelting_deepslate_turquoise_ore' })
	event.remove({ id: 'create:smelting/zinc_ingot_from_ore' })
	event.remove({ id: 'create:smelting/zinc_ingot_from_crushed' })
	event.remove({ id: 'create:smelting/iron_ingot_from_crushed' })
	event.remove({ id: 'create:smelting/gold_ingot_from_crushed' })
	event.remove({ id: 'create:smelting/copper_ingot_from_crushed' })
	event.remove({ id: 'create:blasting/zinc_ingot_from_ore' })
	event.remove({ id: 'create:blasting/zinc_ingot_from_crushed' })
	event.remove({ id: 'create:blasting/iron_ingot_from_crushed' })
	event.remove({ id: 'create:blasting/gold_ingot_from_crushed' })
	event.remove({ id: 'create:blasting/copper_ingot_from_crushed' })
	event.remove({ id: 'create:blasting/silver_ingot_compat_galosphere' })
	event.remove({ id: 'create:smelting/silver_ingot_compat_galosphere' })


//Removing extra cake recipes
	event.remove({ id: 'caverns_and_chasms:cake' })
	event.remove({ id: 'minecraft:cake' })
	event.remove({ id: 'farmersdelight:cake_from_milk_bottle' })

//Removing ghast dough
	event.remove({ id: 'mynethersdelight:ghast_bread_from_smoking' })
	event.remove({ id: 'mynethersdelight:ghast_bread_cooking' })
	event.remove({ id: 'mynethersdelight:ghast_bread_from_campfire_cooking' })

//Unifying bread and pasta
	event.remove({ id: 'minecraft:bread' })
	event.remove({ id: 'farmersdelight:wheat_dough_from_water' })
	event.remove({ id: 'farmersdelight:wheat_dough_from_egg' })
	event.remove({ id: 'minecraft:dough' })
	event.remove({ id: 'farmersdelight:cutting/tag_dough' })
	event.remove({ id: 'farmersdelight:raw_pasta_from_water' })

//Use a cooking pot god damn it
	event.remove({ id: 'minecraft:mushroom_stew' })
	event.remove({ id: 'minecraft:beetroot_soup' })
	event.remove({ id: 'minecraft:rabbit_stew_from_brown_mushroom' })
	event.remove({ id: 'minecraft:rabbit_stew_from_red_mushroom' })
	event.remove({ id: 'mynethersdelight:crafting/rock_soup' })
	event.remove({ id: 'neapolitan:mixed/adzuki_curry' })

//Remove Grindstone polishing
//	event.remove({ id: 'sullysmod:grindstone_polishing/jade_from_deepslate_jade_ore'})
//	event.remove({ id: 'sullysmod:grindstone_polishing/jade_from_jade_ore'})

//Fixing so milling and cutting do different things
	event.remove({ id: 'create:crushing/wool'})
	event.remove({ id: 'minecraft:green_dye'})
	event.remove({ id: 'minecraft:sugar_from_sugar_cane'})
	event.remove({ id: 'minecraft:bone_meal'})
	event.remove({ id: 'minecraft:bone_meal_from_bone_block'})
	event.remove({ id: 'clayworks:green_dye_from_baking'})
//	event.remove({ id: 'species:bone_from_bone_spike'})
//	event.remove({ id: 'species:bone_meal_from_werefang'})
	event.remove({ id: 'mynethersdelight:crafting/sugar_alt'})
	event.remove({ id: 'spawn:bone_meal_from_snail_shell'})
	event.remove({ id: 'autumnity:sugar_from_sap_bottle'})
	event.remove({ id: 'farmersdelight:integration/create/milling/rice_panicle'})
	event.remove({ id: 'farmersdelight:cutting/wheat'})
	event.remove({ id: 'farmersdelight:cutting/crushing/crushing_food/wheat'})
	event.remove({ id: 'farmersdelight:cutting/bone'})
	event.remove({ id: 'farmersdelight:cutting/allium'})
	event.remove({ id: 'farmersdelight:cutting/azure_bluet'})
	event.remove({ id: 'farmersdelight:cutting/blue_orchid'})
	event.remove({ id: 'farmersdelight:cutting/cornflower'})
	event.remove({ id: 'farmersdelight:cutting/dandelion'})
	event.remove({ id: 'farmersdelight:cutting/lily_of_the_valley'})
	event.remove({ id: 'farmersdelight:cutting/orange_tulip'})
	event.remove({ id: 'farmersdelight:cutting/oxeye_daisy'})
	event.remove({ id: 'farmersdelight:cutting/pink_tulip'})
	event.remove({ id: 'farmersdelight:cutting/poppy'})
	event.remove({ id: 'farmersdelight:cutting/red_tulip'})
	event.remove({ id: 'farmersdelight:cutting/torchflower'})
	event.remove({ id: 'farmersdelight:cutting/white_tulip'})
	event.remove({ id: 'farmersdelight:cutting/wither_rose'})
	event.remove({ id: 'abnormals_delight:autumnity/cutting/autumn_crocus'})
	event.remove({ id: 'abnormals_delight:buzzier_bees/cutting/buttercup'})
	event.remove({ id: 'abnormals_delight:buzzier_bees/cutting/pink_clover'})
	event.remove({ id: 'abnormals_delight:buzzier_bees/cutting/white_clover'})
	event.remove({ id: 'abnormals_delight:environmental/cutting/bluebell'})
	event.remove({ id: 'abnormals_delight:environmental/cutting/cartwheel'})
	event.remove({ id: 'abnormals_delight:environmental/cutting/dianthus'})
	event.remove({ id: 'abnormals_delight:environmental/cutting/magenta_hibiscus'})
	event.remove({ id: 'abnormals_delight:environmental/cutting/orange_hibiscus'})
	event.remove({ id: 'abnormals_delight:environmental/cutting/pink_hibiscus'})
	event.remove({ id: 'abnormals_delight:environmental/cutting/purple_hibiscus'})
	event.remove({ id: 'abnormals_delight:environmental/cutting/red_hibiscus'})
	event.remove({ id: 'abnormals_delight:environmental/cutting/red_lotus_flower'})
	event.remove({ id: 'abnormals_delight:environmental/cutting/violet'})
	event.remove({ id: 'abnormals_delight:environmental/cutting/white_lotus_flower'})
	event.remove({ id: 'abnormals_delight:environmental/cutting/yellow_hibiscus'})
	event.remove({ id: 'abnormals_delight:upgrade_aquatic/cutting/pickerelweed'})
	event.remove({ id: 'abnormals_delight:upgrade_aquatic/cutting/pink_searocket'})
	event.remove({ id: 'abnormals_delight:upgrade_aquatic/cutting/white_searocket'})
	event.remove({ id: 'abnormals_delight:atmospheric/cutting/firethorn'})
	event.remove({ id: 'abnormals_delight:atmospheric/cutting/forsythia'})
	event.remove({ id: 'abnormals_delight:atmospheric/cutting/gilia'})
	event.remove({ id: 'abnormals_delight:atmospheric/cutting/hot_monkey_brush'})
	event.remove({ id: 'abnormals_delight:atmospheric/cutting/scalding_monkey_brush'})
	event.remove({ id: 'abnormals_delight:atmospheric/cutting/warm_monkey_brush'})
	event.remove({ id: 'abnormals_delight:atmospheric/cutting/water_hyacinth'})

//Fixing crushing and splashing
	event.remove({ id: 'create:splashing/crushed_raw_copper'})
	event.remove({ id: 'create:splashing/crushed_raw_gold'})
	event.remove({ id: 'create:splashing/crushed_raw_iron'})
	event.remove({ id: 'create:splashing/crushed_raw_zinc'})
	event.remove({ id: 'create:splashing/galosphere/crushed_raw_silver'})
	event.remove({ id: 'create:crushing/diorite_recycling'}) 
	event.remove({ id: 'create:crushing/diorite'})
	event.remove({ id: 'create:crushing/prismarine_crystals'})
	event.remove({ id: 'create:crushing/veridium'})
	event.remove({ id: 'create:crushing/raw_uranium'})
	event.remove({ id: 'create:crushing/tuff'})
	event.remove({ id: 'create:crushing/asurine_recycling'})
	event.remove({ id: 'create:crushing/veridium_recycling'})
	event.remove({ id: 'create:crushing/crimsite'})
	event.remove({ id: 'create:crushing/tuff_recycling'})
	event.remove({ id: 'create:crushing/ochrum'})
	event.remove({ id: 'create:crushing/asurine'})
	event.remove({ id: 'create:crushing/obsidian'})
	event.remove({ id: 'create:crushing/amethyst_block'})
	event.remove({ id: 'create:crushing/amethyst_cluster'})
	event.remove({ id: 'create:crushing/compat/galopshere/amethyst'})
	event.remove({ id: 'create:crushing/compat/galopshere/allurite'})
	event.remove({ id: 'create:crushing/compat/galopshere/lumiere'})
	event.remove({ id: 'create:crushing/compat/quark/moss_block'})

//Simplifying candle holders
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_black'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_blue'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_brown'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_cyan'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_gray'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_green'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_light_blue'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_light_gray'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_lime'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_magenta'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_orange'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_pink'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_purple'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_red'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_white'})
	event.remove({ id: 'supplementaries:candle_holders/candle_holder_yellow'})
	event.remove({ id: 'supplementaries:soap_clean_supplementaries_candle_holder'})

//Food fixing
	event.remove({ id: 'berry_good:sweet_berry_meatballs_from_smoking'})
	event.remove({ id: 'berry_good:sweet_berry_meatballs_from_campfire_cooking'})
	event.remove({ id: 'neapolitan:mint/cooked_mint_chops_from_smoking'})
	event.remove({ id: 'neapolitan:mint/cooked_mint_chops_from_campfire_cooking'})
	event.remove({ id: 'dungeonsdelight:monster_cooking/misc/cob_n_candy_from_string'})
	event.remove({ id: 'farmersdelight:honey_cookies_from_dough'})
	event.remove({ id: 'farmersdelight:honey_cookies_from_wheat'})
	event.remove({ id: 'dungeonsdelight:cooking/dog_food_from_fleshes_tag'})
//	event.remove({ id: 'cavedelight:cooking/primordial_soup'})
	event.remove({ id: 'spawn:cooking/clam_chowder'})
//	event.remove({ id: 'sob:smelting/prickly_pear'})
//	event.remove({ id: 'sob:baking/prickly_pear'})
	event.remove({ id: 'hauntedharvest:mixed_salad'})
	event.remove({ id: 'hauntedharvest:fried_rice_cooking'})
	event.remove({ id: 'incubation:scrambled_eggs'})
	event.remove({ id: 'mynethersdelight:crafting/hot_wings_bucket_alt'})
	event.remove({ id: 'abnormalsdelight:autumnity/cooking/stuffed_pumpkin_block'})

})