		[types.cake.bountifulfares]
			coconut_cake = true
			cocoa_cake = false
			sponge_cake = true

		[types.cake.dungeonsdelight]
			monster_cake = false

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.cake.nomansland]
			fruit_cake = true

		[types.lantern.bountifulfares]
			feldspar_lantern = true

		[types.lantern.dungeonsdelight]
			living_lantern = true

		[types.lantern.caverns_and_chasms]
			cupric_lantern = true
			copper_lantern = true
			exposed_copper_lantern = true
			weathered_copper_lantern = true
			oxidized_copper_lantern = true
			waxed_copper_lantern = true
			waxed_exposed_copper_lantern = true
			waxed_weathered_copper_lantern = true
			waxed_oxidized_copper_lantern = true

		[types.lantern.netherexp]
			treacherous_lantern = true

		[types.lantern.windswept]
			ice_lantern = true

		[types.lantern.wayfarer_core]
			rift_lantern = true

		[types.wood_type.abundant_atmosphere]
			red_bamboo = true
			ashroot = true
			gourdrot = true

		[types.wood_type.dungeonsdelight]
			wormwood = true

		[types.wood_type.sniffed_out]
			vessel = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.quark]
			azalea = false
			ancient = true
			blossom = false

		[types.wood_type.bountifulfares]
			hoary = true
			walnut = false

		[types.wood_type.environmental]
			willow = true
			pine = false
			plum = true
			wisteria = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.autumnity]
			maple = false

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.spawn]
			rotten = true
			date = true
			larch = true
			elm = true

		[types.wood_type.newworld]
			fir = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.netherexp]
			claret = true

		[types.wood_type.windswept]
			holly = true
			chestnut = true
			pine = false

		[types.wood_type.bitsandbalance]
			azalea = false

		[types.wood_type.nomansland]
			pine = true
			maple = true
			walnut = true
			willow = true

		[types.leaves_type.abundant_atmosphere]
			ashroot = true
			gourdrot = true

		[types.leaves_type.bountifulfares]
			apple = false
			flowering_apple = false
			orange = false
			flowering_orange = false
			lemon = false
			flowering_lemon = false
			plum = false
			flowering_plum = false
			hoary = true
			walnut = false
			golden_apple = false
			flowering_golden_apple = false

		[types.leaves_type.cookscollection]
			lemon = false
			fruiting_lemon = false

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = false
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.autumnity]
			maple = false
			yellow_maple = false
			orange_maple = false
			red_maple = false

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = false
			lavender_blossom = false
			orange_blossom = false
			yellow_blossom = false
			red_blossom = false

		[types.leaves_type.spawn]
			date = true
			larch = true
			elm = true

		[types.leaves_type.primal]
			thorny_acacia = true

		[types.leaves_type.newworld]
			fir = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.windswept]
			holly = true
			chestnut = true
			pine = false
			flowering_acacia = true

		[types.leaves_type.galosphere]
			opal = false

		[types.leaves_type.bountifulpears]
			pear = false

		[types.leaves_type.nomansland]
			autumnal_oak = true
			frosted = true
			pale_cherry = true
			red_maple = true
			yellow_birch = true
			pine = true
			maple = true
			walnut = true
			willow = true
			apple_fruit = true
			pear_fruit = true

		[entries.wood_type.another_furniture]
			flower_box = false
			shelf = false
			shutter = false
			bench = false
			table = true
			drawer = false
			chair = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.woodworks]
			trapped_chest = true
			boards = false
			chest = true
			beehive = true
			bookshelf = true
			chiseled_bookshelf = true
			ladder = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = false
			vertical_planks = false
			post = false
			trapped_chest = false
			bookshelf = false
			chest = false
			stripped_post = false
			ladder = false
			vertical_slab = false

		[entries.wood_type.bountifulfares]
			trellis = false
			pickets = true

		[entries.wood_type.envelope]
			pigeonhole = false

		[entries.wood_type.nomansland]
			bookshelf = false
			trimmed_planks = true

		[entries.leaves_type.quark]
			hedge = false
			leaf_carpet = false

		[entries.leaves_type.woodworks]
			leaf_pile = true
