resourcepacks = ["vanilla", "mod_resources", "moonlight:merged_pack", "file/clutternomore", "file/Madpack Assets.zip"]
hiddenresourcepacks = ["programmer_art", "high_contrast"]
distantRendering = true
# Default: 96
# Range: 64 ~ 128
distantRenderDistance = 96
