// kubejsstudio recipes; re-apply merges by recipe id
ServerEvents.recipes(event => {
    event.remove({ id: 'abundant_atmosphere:mossy_basalt_from_vine' })
    event.remove({ id: 'bountifulfares:stick' })
    event.remove({ id: 'mynethersdelight:crafting/stick_alt' })
    event.remove({ id: 'abundant_atmosphere:stick_from_red_bamboo' })
    event.remove({ id: 'woodworks:bamboo_fence_gate_from_bamboo' })
    event.remove({ id: 'farmersdelight:scaffolding_from_canvas' })
    event.remove({ id: 'nomansland:scaffolding' })
    event.remove({ id: 'woodworks:bamboo_fence_from_bamboo' })
    event.remove({ id: 'woodworks:bamboo_ladder_from_bamboo' })
    event.remove({ id: 'mynethersdelight:crafting/basket_alt' })
    event.remove({ id: 'mynethersdelight:cutting/gunpowder_and_stick_cannon' })
    event.remove({ id: 'nomansland:building/mossy_stone_bricks_from_others' })
    event.remove({ id: 'abundant_atmosphere:integration/nomansland/mossy_stone_from_others' })
    event.remove({ id: 'abundant_atmosphere:mossy_stone_from_vine' })
    event.remove({ id: 'nomansland:polished_deepslate' })
    event.remove({ id: 'abundant_atmosphere:mossy_cobbled_deepslate_from_moss_clump' })
    event.remove({ id: 'abundant_atmosphere:mossy_deepslate_bricks_from_moss_clump' })
    event.remove({ id: 'abundant_atmosphere:mossy_deepslate_from_moss_clump' })
    event.remove({ id: 'abundant_atmosphere:mossy_deepslate_tiles_from_moss_clump' })
    event.remove({ id: 'abundant_atmosphere:mossy_polished_deepslate_from_moss_clump' })
    event.remove({ id: 'abundant_atmosphere:shuffled_bricks_from_blocks' })
    event.remove({ id: 'abundant_atmosphere:shuffled_bricks_from_items' })
    event.remove({ id: 'abundant_atmosphere:integration/nomansland/mossy_shuffled_bricks_from_others' })
    event.remove({ id: 'abundant_atmosphere:mossy_shuffled_bricks_from_vine' })
    event.remove({ id: 'create:crafting/materials/andesite_alloy' })
    event.remove({ id: 'simulated:auger_cog_from_auger_shaft' })
    event.remove({ id: 'simulated:auger_shaft_from_auger_cogwheel' })
})
